# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qyx5QdRZ_Jgrh9UcQPTCFYd3tMAYTdwM
"""

h = int(input())

count = 0

for i in range( h+1 ):
    for j in range(60):
        for k in range(60):
            if '3' in  str(i) + str(j) + str(k):
                count += 1

print(count)